# Colors (Noctalia)

[colors.bright]
black = '#2f3732'
blue = '#cdf7d6'
cyan = '#73d0cd'
green = '#61f285'
magenta = '#a6f7ce'
red = '#e46b88'
white = '#ffffff'
yellow = '#f2e661'

[colors.cursor]
cursor = '#98d1a4'
text = '#1c221d'

[colors.normal]
black = '#1c211e'
blue = '#98d1a4'
cyan = '#4daaa7'
green = '#3dcc61'
magenta = '#77d1a4'
red = '#be4663'
white = '#31b295'
yellow = '#ccc03d'

[colors.primary]
background = '#1c211e'
foreground = '#31b295'

[colors.selection]
background = '#98d1a4'
text = '#1c221d'
