color0 #1c211e
color1 #be4663
color2 #3dcc61
color3 #ccc03d
color4 #98d1a4
color5 #77d1a4
color6 #4daaa7
color7 #31b295
color8 #2f3732
color9 #e46b88
color10 #61f285
color11 #f2e661
color12 #cdf7d6
color13 #a6f7ce
color14 #73d0cd
color15 #ffffff
background #1c211e
selection_foreground #1c221d
cursor #98d1a4
cursor_text_color #1c221d
foreground #31b295
selection_background #98d1a4
active_border_color #98d1a4
inactive_border_color #77d1a4

active_tab_foreground   #1c221d
active_tab_background   #98d1a4
inactive_tab_foreground #317f95
inactive_tab_background #2f3732
cursor_trail_color      #317f95
