color0 #1c211e
color1 #fd4663
color2 #3dcc61
color3 #ccc03d
color4 #98b3a1
color5 #96aca2
color6 #98aaa7
color7 #f2f3f2
color8 #2f3732
color9 #ff6079
color10 #61f285
color11 #f2e661
color12 #ced9d2
color13 #ccd2d0
color14 #cfd0d0
color15 #ffffff
background #1c211e
selection_foreground #1c221d
cursor #98b3a1
cursor_text_color #1c221d
foreground #f2f3f2
selection_background #98b3a1
active_border_color #98b3a1
inactive_border_color #96aca2

active_tab_foreground   #1c221d
active_tab_background   #98b3a1
inactive_tab_foreground #b0b5b2
inactive_tab_background #2f3732
cursor_trail_color      #b0b5b2
